### ISSUE TITLE
Long 'onCreate'

### ISSUE THREAD

**Issue by cngondo** [Markmwaura/FlashLight#1]
When you override the 'onCreate' method as you launch you activity, make sure that you do not have a hell lot of code in there as the startup will be slow and it's bad for your users. Take into consideration the load time startup of your app. 
Check out [App Launch Time 101](https://www.youtube.com/watch?v=Vw1G1s73DsY) and experiment this on your app.

**Comment by Markmwaura** [comment]
Found a work around it.
